### ISSUE TITLE
Can't override `from` when sending

### ISSUE THREAD

**Issue by lucsky** [esendex/esendex-go-sdk#4]
The REST API specifies that it is possible to override "the originator that the message appears to originate from" (source: https://developers.esendex.com/api-reference#messagedispatcher) for all messages sent from a call to `messagedispatcher` or on a per message basis.

However, the `Message` type does not provide a way to specify this information even though it does allow most of the others. Is there a specific reason for this omission ?

**Comment by moretonb** [comment]
You are right, you can override the originator of a message. I don't think there was a reason Josh purposefully omitted it. I can raise a story for the team to look at on the backlog. Alternatively if you are keen to have the feature soon I am more than happy to review a PR 😸

Thanks @lucsky

**Comment by lucsky** [comment]
Sure thing, I'm glad you accept PRs. There you go: #5 😃

**Comment by moretonb** [comment]
Accepted, thank you very much lucsky 🍰
